### GET request to example server
GET http://localhost:8080/api/employees

### Create employee
POST http://localhost:8080/api/employees
Content-Type: application/json

{
  "firstName": "Carson",
  "lastName": "Marrero",
  "email": "Carson@test.com",
  "phoneNumber": "123-456-7890"
}

### Get employee by ID
GET http://localhost:8080/api/employees/1


### Delete employee
DELETE http://localhost:8080/api/employees/5

### Edit Employee - by single parameter or all parameters.
PATCH http://localhost:8080/api/employees/4
Content-Type: application/json

{
  "role": "Child"
}